In [32]:
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
# Load all the csv files as data frames

df1 = pd.read_csv('Australia_Wine_Stats.csv')
df2 = pd.read_csv('Chile_Wine_Stats.csv')
df3 = pd.read_csv('Italy_Wine_Stats.csv')
df4 = pd.read_csv('France_Wine_Stats.csv')
df5 = pd.read_csv('New Zealand_Wine_Stats.csv')
df6 = pd.read_csv('Portugal_Wine_Stats.csv')
df7 = pd.read_csv('Spain_Wine_Stats.csv')
df8 = pd.read_csv('USA_Wine_Stats.csv')

# Combine all the data frames into a single data frame

wine_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], ignore_index=True)

In [34]:
# First rows of the data frame
wine_df.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890

In [35]:
# Information of the data frame
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5145 non-null   int64
 1   Name               5145 non-null   object
 2   Rating             5145 non-null   float64
 3   Number of Ratings  5145 non-null   int64
 4   Price              5145 non-null   float64
 5   Region             5145 non-null   object
 6   Winery             5142 non-null   object
 7   Wine style         4624 non-null   object
 8   Alcohol content    5145 non-null   float64
 9   Grapes             2977 non-null   object
 10  Food pairings      5145 non-null   object
 11  Bold               5145 non-null   float64
 12  Tannin             5145 non-null   float64
 13  Sweet              5145 non-null   float64
 14  Acidic             5145 non-null   float64
dtypes: float64(7), int64(2), object(6)
memory usage: 603.1+ KB

In [36]:
# Remove duplicate records
wine_df.drop_duplicates()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5140,667,Katherine Goldschmidt Stonemason Hill Cabernet...,4.1,80,25.99,United States / California / North Coast / Son...,Goldschmidt Vineyards,Californian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",82.71,48.87000,7.37,43.770
5141,668,Pessimist Red Blend 2020,4.0,574,17.99,United States / California / Central Coast / S...,DAOU,Californian Red Blend,15.200000,100 Durif,"['Beef', 'Lamb', 'Veal', 'Poultry']",85.00,53.43000,15.96,61.840
5142,669,Cabernet Sauvignon 2013,3.8,4612,34.99,United States / California / Central Coast / S...,Liberty School,Californian Cabernet Sauvignon,13.500000,100 Cabernet Sauvignon,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,49.14000,9.63,42.020
5143,670,Petit Verdot 2017,4.2,53,34.99,United States / California / Central Coast / S...,Opaque,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
5144,671,Freakshow Chardonnay 2020,3.8,160,17.99,United States / California / Central Valley / ...,Michael David Winery,Californian Chardonnay,13.500000,100 Chardonnay,"['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...",77.65,46.29527,33.83,47.480

In [37]:
# Remove null records
wine_df.dropna()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.5,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.00
5,5,Passion has Red Lips 2014,3.8,648,18.49,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,14.5,"70 Shiraz/Syrah, 30 Cabernet Sauvignon","['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.78
7,7,Jester Shiraz 2018,3.9,658,22.00,Australia / South Australia / Fleurieu / McLar...,Mitolo,Australian Shiraz,14.5,100 Shiraz/Syrah,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,46.65000,19.07,44.18
8,8,Shotfire Quartage 2016,3.8,93,17.99,Australia / South Australia / Barossa,Thorn-Clarke,Australian Bordeaux Blend,14.5,"Cabernet Franc, Malbec, Cabernet Sauvignon","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...",85.00,56.40000,10.85,65.28
9,9,Stonehorse Shiraz 2018,4.0,288,29.17,Australia / South Australia / Barossa / Baross...,Kaesler,Australian Shiraz,14.0,100 Shiraz/Syrah,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",84.04,44.21000,22.10,41.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5138,665,Sonoma Coast Pinot Noir 2013,4.1,193,39.99,United States / California / North Coast / Son...,Red Car,Californian Pinot Noir,13.3,100 Pinot Noir,"['Beef', 'Veal', 'Game (deer, venison)', 'Poul...",38.89,19.57000,7.58,54.96
5139,666,Dry Riesling 2015,3.9,184,24.99,United States / California / North Coast / Nap...,Trefethen,Californian Riesling,12.5,100 Riesling,"['Pork', 'Shellfish', 'Spicy food', 'Poultry',...",41.61,46.29527,1.21,69.68
5141,668,Pessimist Red Blend 2020,4.0,574,17.99,United States / California / Central Coast / S...,DAOU,Californian Red Blend,15.2,100 Durif,"['Beef', 'Lamb', 'Veal', 'Poultry']",85.00,53.43000,15.96,61.84
5142,669,Cabernet Sauvignon 2013,3.8,4612,34.99,United States / California / Central Coast / S...,Liberty School,Californian Cabernet Sauvignon,13.5,100 Cabernet Sauvignon,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,49.14000,9.63,42.02
5144,671,Freakshow Chardonnay 2020,3.8,160,17.99,United States / California / Central Valley / ...,Michael David Winery,Californian Chardonnay,13.5,100 Chardonnay,"['Pork', 'Rich fish (salmon, tuna etc)', 'Vege...",77.65,46.29527,33.83,47.48

In [38]:
# Interquartile Range to remove outliers
def remove_outliers(wine_df, column):
    Q1 = wine_df[column].quantile(0.25)  # 25th percentile
    Q3 = wine_df[column].quantile(0.75)  # 75th percentile
    IQR = Q3 - Q1                   # Interquartile Range
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return wine_df[(wine_df[column] >= lower_bound) & (wine_df[column] <= upper_bound)]

In [39]:
# Remove outliers
wine_df = remove_outliers(wine_df, 'Rating')
wine_df = remove_outliers(wine_df, 'Number of Ratings')
wine_df = remove_outliers(wine_df, 'Price')
wine_df = remove_outliers(wine_df, 'Alcohol content')
wine_df = remove_outliers(wine_df, 'Bold')
wine_df = remove_outliers(wine_df, 'Tannin')
wine_df = remove_outliers(wine_df, 'Sweet')
wine_df = remove_outliers(wine_df, 'Acidic')

In [40]:
# First rows of the data set after removing outliers
wine_df.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890

In [41]:
# Data points that lie far from the bulk of the data (Deviated) are the outliers. These are not errors, 
# but rather rare occurrences that are far from the central tendency.

In [42]:
# Extract the country from the 'Region' column
wine_df["Country"] = wine_df["Region"].apply(lambda x: x.split(" / ")[0])

In [43]:
# Function to extract country region
def extract_country_region(region):
    parts = region.split('/')
    if len(parts) > 1:
        return parts[1].strip()  # Return the second part as country region
    return None  # Handle cases where region data might be malformed

# Add the Country_region column
wine_df['Country_region'] = wine_df['Region'].apply(extract_country_region)

In [44]:
# Details of the data set after extracting from the region column
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2174 entries, 0 to 5143
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2174 non-null   int64
 1   Name               2174 non-null   object
 2   Rating             2174 non-null   float64
 3   Number of Ratings  2174 non-null   int64
 4   Price              2174 non-null   float64
 5   Region             2174 non-null   object
 6   Winery             2172 non-null   object
 7   Wine style         1703 non-null   object
 8   Alcohol content    2174 non-null   float64
 9   Grapes             878 non-null    object
 10  Food pairings      2174 non-null   object
 11  Bold               2174 non-null   float64
 12  Tannin             2174 non-null   float64
 13  Sweet              2174 non-null   float64
 14  Acidic             2174 non-null   float64
 15  Country            2174 non-null   object
 16  Country_region     2170 non-null   object
dtypes: float64(7), int64(2), object(8)
memory usage: 305.7+ KB

In [45]:
# Define the unique food items (you can extend this list as needed)
food_items = ['Beef','Lamb', 'Poultry', 'Pasta']

# Create new columns for each food item
for food in food_items:
    wine_df[food] = wine_df['Food pairings'].apply(lambda x: True if food in x else False)

# Display the updated DataFrame
print(wine_df)

      Unnamed: 0                                               Name  Rating  \
0              0                          Fields Of Joy Shiraz 2014     4.0
1              1                                  Shotfire GSM 2018     3.9
2              2                          Passion has Red Lips 2020     3.8
3              3           The Hermit Crab Viognier - Marsanne 2018     3.8
4              4          Cabernet Sauvignon (Batch No. 1 & 3) 2019     3.8
...          ...                                                ...     ...
5131         658                                  Chenin Blanc 2020     4.0
5133         660                                   Limited Red 2018     4.0
5137         664                           Julia's Dazzle Rosé 2021     3.9
5140         667  Katherine Goldschmidt Stonemason Hill Cabernet...     4.1
5143         670                                  Petit Verdot 2017     4.2

      Number of Ratings  Price  \
0                   203  28.99
1                    36  19.49
2                   350  27.50
3                  1026  16.99
4                   969  14.99
...                 ...    ...
5131                 31  16.99
5133                657  26.70
5137                 31  16.99
5140                 80  25.99
5143                 53  34.99

                                                 Region  \
0     Australia / South Australia / Mount Lofty Rang...
1                 Australia / South Australia / Barossa
2     Australia / South Australia / Fleurieu / McLar...
3     Australia / South Australia / Fleurieu / McLar...
4                   Australia / South Eastern Australia
...                                                 ...
5131       United States / Washington / Columbia Valley
5133  United States / California / North Coast / Nap...
5137  United States / Washington / Columbia Valley /...
5140  United States / California / North Coast / Son...
5143  United States / California / Central Coast / S...

                      Winery                      Wine style  Alcohol content  \
0                  Two Hands               Australian Shiraz        13.794543
1               Thorn-Clarke      Australian Rhône Blend Red        14.500000
2           Some Young Punks    Australian Cabernet - Shiraz        13.794543
3                 d'Arenberg                             NaN        13.794543
4     Gentleman's Collection   Australian Cabernet Sauvignon        13.794543
...                      ...                             ...              ...
5131         Kiona Vineyards                             NaN        13.794543
5133                   Decoy           Californian Red Blend        13.794543
5137            Long Shadows                             NaN        13.794543
5140   Goldschmidt Vineyards  Californian Cabernet Sauvignon        13.794543
5143                  Opaque                             NaN        13.794543

                                 Grapes  ...   Bold    Tannin  Sweet  Acidic  \
0                                   NaN  ...  85.00  47.13000  20.62  43.570
1     Mourvedre, Shiraz/Syrah, Grenache  ...  85.00  50.63000   9.05  43.000
2                                   NaN  ...  85.00  49.37000   8.19  44.780
3                                   NaN  ...  61.73  46.29527   9.05  53.555
4                                   NaN  ...  76.34  49.36000  16.02  47.890
...                                 ...  ...    ...       ...    ...     ...
5131                                NaN  ...  61.73  46.29527   9.05  53.555
5133                                NaN  ...  80.58  47.78000  12.39  58.060
5137                                NaN  ...  61.73  46.29527   9.05  53.555
5140                                NaN  ...  82.71  48.87000   7.37  43.770
5143                                NaN  ...  61.73  46.29527   9.05  53.555

            Country           Country_region   Beef   Lamb  Poultry  Pasta
0         Australia          South Australia   True   True     True  False
1         Australia          South Australia   True   True    False   True
2         Australia          South Australia   True   True     True  False
3         Australia          South Australia  False  False    False  False
4         Australia  South Eastern Australia   True   True     True  False
...             ...                      ...    ...    ...      ...    ...
5131  United States               Washington  False  False    False  False
5133  United States               California   True   True     True  False
5137  United States               Washington  False  False    False  False
5140  United States               California   True   True     True  False
5143  United States               California  False  False    False  False

[2174 rows x 21 columns]

In [46]:
# Remove irrelevant columns
wine_df = wine_df.drop(columns=['Region', 'Grapes'])

In [ ]:
# Reasons
# Region column is extracted in to two new columns country and country_region
# Grapes column has null values

In [47]:
# Information of the data set after removing irrelevant columns
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2174 entries, 0 to 5143
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2174 non-null   int64
 1   Name               2174 non-null   object
 2   Rating             2174 non-null   float64
 3   Number of Ratings  2174 non-null   int64
 4   Price              2174 non-null   float64
 5   Winery             2172 non-null   object
 6   Wine style         1703 non-null   object
 7   Alcohol content    2174 non-null   float64
 8   Food pairings      2174 non-null   object
 9   Bold               2174 non-null   float64
 10  Tannin             2174 non-null   float64
 11  Sweet              2174 non-null   float64
 12  Acidic             2174 non-null   float64
 13  Country            2174 non-null   object
 14  Country_region     2170 non-null   object
 15  Beef               2174 non-null   bool
 16  Lamb               2174 non-null   bool
 17  Poultry            2174 non-null   bool
 18  Pasta              2174 non-null   bool
dtypes: bool(4), float64(7), int64(2), object(6)
memory usage: 280.2+ KB